services:
  app-dev:
    container_name: trmm-app-dev
    image: node:20-alpine
    restart: always
    command: /bin/sh -c "npm install --cache ~/.npm && npm i -g @quasar/cli && npm run serve"
    working_dir: /workspace/web
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:9000"
    environment:
      - DEV_URL=${DEV_URL:-https://api.rmadm.org}
      - DEV_HOST=0.0.0.0
      - DEV_PORT=9000
      - USE_HTTPS=${USE_HTTPS:-false}
      - DOCKER_BUILD=true
    extra_hosts:
      - "api.rmadm.org:95.142.43.25"
      - "app.rmadm.org:95.142.43.25"
      - "mesh.rmadm.org:95.142.43.25"
    networks:
      - dev

networks:
  dev:
    driver: bridge
