syntax = "proto3";

import "common/user.proto";
import "common/policy.proto";
import "common/node.proto";
import "common/target.proto";
import "common/export.proto";

import "google/protobuf/wrappers.proto";

package laborato.mesh.operator.v1;

option csharp_namespace = "LaboratoMDM.Mesh.Master.Grpc.Operator.V1";

// ENUMS

enum PolicyScope {
  POLICY_SCOPE_NONE = 0;
  POLICY_SCOPE_USER = 1;
  POLICY_SCOPE_MACHINE = 2;
  POLICY_SCOPE_BOTH = 3;
}

enum PolicyDesiredState {
  POLICY_DESIRED_STATE_UNSPECIFIED = 0;
  POLICY_DESIRED_STATE_ENABLED = 1;
  POLICY_DESIRED_STATE_DISABLED = 2;
}

enum PolicySource {
  POLICY_SOURCE_UNSPECIFIED = 0;
  POLICY_SOURCE_GLOBAL = 1;
  POLICY_SOURCE_AGENT = 2;
  POLICY_SOURCE_USER = 3;
}

// AGENTS

service AgentService {
  rpc ListAgents (ListAgentsRequest)
      returns (ListAgentsResponse);

  rpc GetAgent (GetAgentRequest)
      returns (AgentDetails);

  rpc UpdateAgent(UpdateAgentRequest)
      returns(UpdateAgentResponse);
}

message UpdateAgentResponse {}

message UpdateAgentRequest{
    string id = 1;
    string description = 2;
    int32 max_policies = 3;
}

message ListAgentsRequest {}

message GetAgentRequest {
  string agent_id = 1;
}

message ListAgentsResponse {
  repeated AgentSummary agents = 1;
}

message AgentSummary {
  string agent_id = 1;
  string host_name = 2;
  string ip_address = 3;
  bool is_online = 4;
  int64 last_heartbeat_unix = 5;
}

message AgentDetails {
  string agent_id = 1;
  string host_name = 2;
  string ip_address = 3;

  bool is_online = 4;
  int64 last_heartbeat_unix = 5;

  laborato.common.node.NodeFullInfo node_info = 6;
}

//Collections
service CollectionsControlService {
  rpc GetAllCollections (GetAllCollectionsRequest)
      returns (GetAllCollectionsResponse);
  rpc GetCollectionById (GetCollectionByIdRequest)
      returns (CollectionDetailsResponse);
  rpc CreateCollectionsPolicies (CreateCollectionsPoliciesRequest)
      returns (CreateCollectionsPoliciesResponse);
  rpc CreateCollection (CreateCollectionRequest)
      returns (CollectionDetailsResponse);
  rpc UpdateCollection(UpdateCollectionRequest)
      returns (CollectionDetailsResponse);
  rpc DeleteCollection (DeleteCollectionRequest)
      returns (DeleteCollectionResponse);
  rpc GetPoliciesInCollection (GetPoliciesInCollectionRequest)
      returns (GetPoliciesInCollectionResponse);
  rpc RemovePoliciesFromCollection(RemovePoliciesFromCollectionRequest)
      returns (DeleteCollectionResponse);
  // Получение коллекций, примененных к агенту, пользователю или группе
  rpc GetAppliedCollectionsByAgent (GetAppliedCollectionsByAgentRequest)
      returns (GetAppliedCollectionsResponse);
  rpc GetAppliedCollectionsByUser (GetAppliedCollectionsByUserRequest)
      returns (GetAppliedCollectionsResponse);
  rpc GetAppliedCollectionsByGroup (GetAppliedCollectionsByGroupRequest)
     returns (GetAppliedCollectionsResponse);
  rpc GetAppliedCollectionsByAgentCategory(GetAppliedCollectionsByAgentCategoryRequest)
     returns (GetAppliedCollectionsResponse);
}

message GetAppliedCollectionsByAgentCategoryRequest {
    int64 category_id = 1;
    string lang_code = 2;
}

message GetAppliedCollectionsByAgentRequest {
  string agent_id = 1;
  string lang_code = 2;
}

message GetAppliedCollectionsByUserRequest {
  string user_id = 1; // Guid в строке
  string lang_code = 2;
}

message GetAppliedCollectionsByGroupRequest {
  string group_id = 1; // Guid в строке
  string lang_code = 2;
}

message GetAppliedCollectionsResponse {
  repeated CollectionsSummary collections = 1;
}

message CreateCollectionsPoliciesRequest {
  int64 collection_id = 1;
  repeated PolicyConfigureModel policies = 2;
}

message PolicyConfigureModel {
  string hash = 1;
  bool state = 2;
  laborato.common.policy.PolicySelection selection = 3;
}

message CreateCollectionsPoliciesResponse {
  bool success = 1;
  string message = 2;
}

message GetAllCollectionsRequest {
  string lang_code = 1;
  optional PolicyScope scope = 2;
}

message GetAllCollectionsResponse {
  repeated CollectionsSummary collections = 1;
}

message GetCollectionByIdRequest {
  int64 collection_id = 1;
  string lang_code = 2;
}

message CollectionDetailsResponse {
  CollectionsSummary collection = 1;
}

message CollectionsSummary {
  int64 id = 1;
  PolicyScope scope = 2;
  string name = 3;
  string explain_text = 4;
  repeated PolicySummary policies = 5;
}

message CreateCollectionRequest {
  string name = 1;
  PolicyScope scope = 2;
  string explain_text = 3;
  repeated CollectionTranslation translations = 4;
}

message UpdateCollectionRequest {
    int64 id = 1;
    string name = 2;
    string explain_text = 3;
    repeated CollectionTranslation translations = 4;
}

message CollectionTranslation {
  string lang_code = 1;
  string name = 2;
  string explain_text = 3;
}

message DeleteCollectionRequest {
  int64 collection_id = 1;
}

message DeleteCollectionResponse {
  bool success = 1;
  string message = 2;
}

message GetPoliciesInCollectionRequest {
  int64 collection_id = 1;
  string lang_code = 2;
}

message GetPoliciesInCollectionResponse {
  repeated PolicySummary policies = 1;
}

message RemovePoliciesFromCollectionRequest {
  int64 collectionId = 1;
  repeated string policies = 2;
}

// USERS

service UserService {
  rpc ListUsersForAgent (ListUsersForAgentRequest)
      returns (ListUsersForAgentResponse);

  rpc ListUserGroupsForAgent (ListUserGroupsForAgentRequest)
      returns (ListUserGroupsForAgentResponse);
}

message ListUsersForAgentRequest {
  string agent_id = 1;
}

message ListUsersForAgentResponse {
  repeated laborato.common.user.UserInfo users = 1;
}

message ListUserGroupsForAgentRequest {
    string agent_id = 1;
}

message ListUserGroupsForAgentResponse {
    repeated laborato.common.user.GroupInfo groups = 1;
}


// ADMX FILES

service AdmxService {
  rpc ListAdmxFiles (ListAdmxFilesRequest)
      returns (ListAdmxFilesResponse);

  rpc GetAdmxSnapshot (GetAdmxSnapshotRequest)
      returns (AdmxSnapshot);

  rpc ImportAdmxZip (ImportAdmxZipRequest)
      returns (ImportAdmxResponse);

  rpc ImportAdmxFile (ImportAdmxFileRequest)
    returns (ImportAdmxResponse);
}

message ImportAdmxZipRequest {
  bytes zip_content = 1; // сам zip-файл
}

message ImportAdmxFileRequest {
  bytes file_content = 1; // содержимое файла
  string file_name = 2; // имя файла, например "test.admx"
}

message ImportAdmxResponse {
  bool success = 1;
  string message = 2;
}

message ListAdmxFilesRequest {}

message ListAdmxFilesResponse {
  repeated AdmxFile files = 1;
}

message GetAdmxSnapshotRequest {
  string file_hash = 1;
}

message AdmxFile {
  string file_name = 1;
  string file_hash = 2;
  int64 loaded_at_unix = 3;
}

message PolicyCategory {
  string name = 1;
  string display_name = 2;
  string explain_text = 3;
  string parent_category_name = 4;
}

message PolicyNamespace {
  string prefix = 1;
  string namespace = 2;
}

message AdmxSnapshot {
  AdmxFile file = 1;
  repeated PolicyDescriptor policies = 2;
  repeated PolicyCategory categories = 3;
  repeated PolicyNamespace namespaces = 4;
}


// POLICY CATALOG

service PolicyCatalogService {
  rpc GetPolicy (GetPolicyRequest)
      returns (PolicyDescriptor);

  rpc ListPoliciesGroupedByScope (ListPoliciesGroupedByScopeRequest)
      returns (ListPoliciesGroupedByScopeResponse);

  rpc ExportAllPolicies(ExportAllPoliciesRequest)
      returns (laborato.common.export.ExportResponse);

  rpc GetCategoryTree(GetCategoryTreeRequest)
      returns (GetCategoryTreeResponse);

  rpc GetPoliciesByCategory(GetPoliciesByCategoryRequest)
      returns (GetPoliciesByCategoryResponse);

  rpc GetPoliciesByAdmx(GetPoliciesByAdmxRequest)
      returns (GetPoliciesByAdmxResponse);

  rpc GetPolicyDetails (GetPolicyDetailsRequest)
      returns (PolicyDetails);

  rpc SearchPolicyShort (SearchPolicyShortRequest)
      returns (SearchPolicyShortResponse);
}

message SearchPolicyShortRequest {
    string search = 1;
    string lang_code = 2;
}

message SearchPolicyShortResponse {
    string lang_code = 1;
    repeated PolicySummary policies = 2;
}

message ExportAllPoliciesRequest {
    laborato.common.export.ExportFormat export_format = 1;
}

message GetPoliciesByAdmxRequest {
   string lang_code = 1;
   string admx_file = 2;
}

message GetPoliciesByAdmxResponse {
    string lang_code = 1;
    string admx_file = 2;
    repeated PolicySummary policies = 3;
}

message GetPoliciesByCategoryRequest {
    string lang_code = 1;
    string category = 2;
}

message GetPoliciesByCategoryResponse {
    string lang_code = 1;
    repeated PolicySummary policies = 2;
}

message GetCategoryTreeRequest {
  string lang_code = 1; // язык для перевода displayName
}

message GetCategoryTreeResponse {
  string lang_code = 1; // язык для перевода displayName
  repeated CategoryView categories = 2;
}

message CategoryView {
    int32 id = 1;
    string category_name = 2;
    string display_name = 3;
    repeated CategoryView childs = 4;
}

message ListPoliciesRequest {
  string admx_file_hash = 1;
}

message ListPoliciesResponse {
  repeated PolicyDescriptor policies = 1;
}

message GetPolicyRequest {
  string policy_hash = 1;
}

message ListPoliciesGroupedByScopeRequest {
  string lang_code = 1; // язык для перевода displayName
}

message GetPolicyDetailsRequest {
  int64 policy_id = 1;
  string lang_code = 2;
}

message PolicyDetails {
  PolicyDetailsPolicy policy = 1;
  PolicyPresentation presentation = 2;
  repeated PolicyDetailsElement policy_elements = 3;
}

message PolicyDetailsPolicy {
  int64 id = 1;
  string name = 2;
  string hash = 3;
  string scope = 4;

  optional string parent_category_ref = 5;
  optional string supported_on_ref = 6;
  optional google.protobuf.StringValue client_extension = 7;
}

message PolicyPresentation {
  int32 id = 1;
  string presentation_id = 2;
  string adml_file = 3;
  repeated PolicyPresentationElement elements = 4;
}

message PolicyPresentationElement {
  int32 id = 1;
  string type = 2;
  string ref_id = 3;
  optional google.protobuf.Int32Value parent_element_id = 4;
  optional google.protobuf.StringValue default_value = 5;
  optional google.protobuf.StringValue text = 6;
}

message PolicyDetailsElement {
  int32 id = 1;
  string element_id = 2;
  string type = 3;

  optional google.protobuf.StringValue value_name = 4;
  optional google.protobuf.StringValue registry_key = 5;
  optional google.protobuf.BoolValue required = 6;
  optional google.protobuf.Int32Value max_length = 7;

  optional google.protobuf.StringValue max_strings = 8;
  optional google.protobuf.BoolValue expandable = 9;

  optional google.protobuf.Int64Value min_value = 10;
  optional google.protobuf.Int64Value max_value = 11;

  optional google.protobuf.StringValue value_prefix = 12;
  optional google.protobuf.BoolValue explicit_value = 13;
  optional google.protobuf.BoolValue additive = 14;

  repeated PolicyDetailsElementItem items = 15;
}

message PolicyDetailsElementItem {
  int32 id = 1;
  string name = 2;
  string parent_type = 3;
  string type = 4;
  string value_type = 5;

  optional google.protobuf.StringValue value_name = 6;
  optional google.protobuf.BoolValue required = 7;
  optional google.protobuf.Int32Value parent_id = 8;
  optional google.protobuf.StringValue display_name = 9;
  string value = 10;
}

message ListPoliciesGroupedByScopeResponse {
  repeated PolicyGroup groups = 1;
}

message PolicyDescriptor {
  string policy_hash = 1;
  string name = 2;

  PolicyScope scope = 3;

  string registry_key = 4;
  string value_name = 5;

  string enabled_value = 6;
  string disabled_value = 7;

  string supported_on_ref = 8;
  string parent_category = 9;
  string presentation_ref = 10;

  repeated PolicyElement elements = 11;
  repeated string required_capabilities = 12;
  repeated string required_hardware = 13;

  repeated string admx_file_hashes = 14;
}

message PolicyElement {
  string id_name = 1;
  string type = 2;

  string value_name = 3;
  int32 max_length = 4;
  bool required = 5;

  string client_extension = 6;
}

message PolicyGroup {
  string scope = 1; // например "User", "Machine", "Both", "None"
  repeated PolicySummary policies = 2;
}

message PolicySummary {
  int64 id = 1;
  string name = 2;
  string display_name = 3;
  string explain_text = 4;
  PolicyScope scope = 5;
}

// POLICY ASSIGNMENT

service PolicyAssignmentService {
  rpc AssignPolicy (AssignPolicyRequest)
      returns (AssignPolicyResponse);

  rpc RemovePolicy (RemovePolicyRequest)
      returns (RemovePolicyResponse);

  rpc AssignPolicyCollection(AssignPolicyCollectionRequest)
    returns (AssignPolicyCollectionResponse);

 rpc RemovePolicyCollection(RemovePolicyCollectionRequest)
    returns (RemovePolicyCollectionResponse);

}
message AssignPolicyCollectionRequest {
  int64 collection_id = 1;
  laborato.common.target.Target target = 2;
  laborato.common.policy.PolicySelection selection = 3;
}
message AssignPolicyCollectionResponse {}

message RemovePolicyCollectionRequest {
  int64 collection_id = 1;
  laborato.common.target.Target target = 2;
}
message RemovePolicyCollectionResponse {}

message AssignPolicyRequest {
  string policy_hash = 1;
  laborato.common.target.Target target = 2;
  laborato.common.policy.PolicySelection selection = 3;
}


message AssignPolicyResponse {}

message RemovePolicyRequest {
  string policy_hash = 1;
  laborato.common.target.Target target = 2;
}

message RemovePolicyResponse {}

message PolicyValueOverride {
  oneof value {
    int32 dword = 1;
    string string_value = 2;
  }
}


// POLICY STATE / AUDIT

service PolicyStateService {
  rpc GetEffectivePolicies (GetEffectivePoliciesRequest)
      returns (GetEffectivePoliciesResponse);

  rpc GetAssignments (GetAssignmentsRequest)
      returns (GetAssignmentsResponse);

  rpc ExportAssignments(ExportPolicyStateRequest)
      returns (laborato.common.export.ExportResponse);

  rpc ExportEffectivePolicies(ExportPolicyStateRequest)
      returns (laborato.common.export.ExportResponse);
}

message ExportPolicyStateRequest {
    laborato.common.target.Target target = 1;
    laborato.common.export.ExportFormat export_format = 2;
}

message GetEffectivePoliciesRequest {
  laborato.common.target.Target target = 1;
  string lang_code = 2;
}

message GetEffectivePoliciesResponse {
  repeated EffectivePolicy policies = 1;
}

message EffectivePolicy {
  string policy_hash = 1;
  PolicySource source = 2;
  string userSid = 3;
  PolicySummary summary = 4;
}

message GetAssignmentsRequest {
  laborato.common.target.Target target = 1;
  string lang_code = 2;
}

message GetAssignmentsResponse {
  repeated PolicyAssignment assignments = 1;
}

message PolicyAssignment {
  string policy_hash = 1;
  PolicyDesiredState desired_state = 2;
  PolicyValueOverride override = 3;
  laborato.common.target.Target target = 4;
  string sid = 5;
  PolicySummary summary = 6;
}
