syntax = "proto3";

import "common/user.proto";
import "operator.proto";

import "google/protobuf/wrappers.proto";

package laborato.operator.service;

service OperatorUserControlService {
    rpc CreateUser(CreateUserRequest) returns (UserControlResponse);
    rpc UpdateUser(UpdateUserRequest) returns (UserControlResponse);
    rpc DeleteUser(UserIdentifier) returns (UserControlResponse);
    rpc EnableUser(EnableUserRequest) returns (UserControlResponse);
    rpc SetUserPassword(SetUserPasswordRequest) returns (UserControlResponse);
    rpc UnlockUser(UserIdentifier) returns (UserControlResponse);
    rpc ExpireUserPassword(UserIdentifier) returns (UserControlResponse);
    rpc SetUserAccountExpiration(SetUserAccountExpirationRequest) returns (UserControlResponse);
    rpc CreateGroup(CreateUserGroupRequest) returns (UserControlResponse);
    rpc DeleteGroup(GroupRequest) returns (UserControlResponse);
    rpc AddUserToGroup(UserGroupRequest) returns (UserControlResponse);
    rpc RemoveUserFromGroup(UserGroupRequest) returns (UserControlResponse);

    rpc GetUserEffectiveAgents(UserIdentifier) returns (UserAgentsResponse);
    rpc SetGroupChildGroups(SetGroupChildGroupsRequest) returns (UserControlResponse);

    // ===== USER READ =====
    rpc GetUser(UserIdentifier) returns (UserResponse);
    rpc GetAllUsers(UserGroupTarget) returns (UsersResponse);
    rpc GetUserGroups(UserIdentifier) returns (GroupListResponse);
    rpc GetUserAgents(UserIdentifier) returns (UserAgentsResponse);

    // ===== GROUP READ =====
    rpc GetGroup(GroupRequest) returns (GroupResponse);
    rpc GetAllGroups(UserGroupTarget) returns (GroupsResponse);
    rpc GetGroupUsers(GroupRequest) returns (UserListResponse);
    rpc GetGroupAgents(GroupRequest) returns (AgentListResponse);
    rpc GetGroupChildGroups(GroupRequest) returns (GroupListResponse);
    rpc GetGroupParentGroups(GroupRequest) returns (GroupListResponse);
}

message CreateUserRequest {
    UserGroupTarget target = 1;
    laborato.common.user.UserRequest user = 2;
}

message UpdateUserRequest {
    UserIdentifier user = 1;
    laborato.common.user.UserRequest data = 3;
}

message EnableUserRequest {
    UserIdentifier user = 1;
    bool enable = 2;
}

message SetUserPasswordRequest {
    UserIdentifier user = 1;
    string new_password = 2;
}

message SetUserAccountExpirationRequest {
    UserIdentifier user = 1;
    google.protobuf.StringValue account_expiration_date = 2; // ISO 8601
}

message UserIdentifier {
    UserGroupTarget target = 1;
    string sam_id = 2;
}

message SetGroupChildGroupsRequest {
    GroupRequest group = 1;
    repeated string child_group_ids = 2;
}


message UserControlResponse {
    ResponseStatus status = 1;
    optional string error_message = 2;
}

message UserAgentsResponse {
    ResponseStatus status = 1;
    repeated string agent_ids = 2;
    optional string error_message = 3;
}

message UserResponse {
    ResponseStatus status = 1;
    laborato.common.user.UserInfo user = 2;
    optional string error_message = 3;
}

message UsersResponse {
    ResponseStatus status = 1;
    repeated laborato.common.user.UserInfo users = 2;
    optional string error_message = 3;
}

message GroupResponse {
    ResponseStatus status = 1;
    laborato.common.user.GroupInfo group = 2;
    optional string error_message = 3;
}

message GroupsResponse {
    ResponseStatus status = 1;
    repeated laborato.common.user.GroupInfo groups = 2;
    optional string error_message = 3;
}

message GroupListResponse {
    ResponseStatus status = 1;
    repeated laborato.common.user.GroupInfo groups = 2;
    optional string error_message = 3;
}

message UserListResponse {
    ResponseStatus status = 1;
    repeated laborato.common.user.UserInfo users = 2;
    optional string error_message = 3;
}

message AgentListResponse {
    ResponseStatus status = 1;
    repeated string agent_ids = 2;
    optional string error_message = 3;
}


enum ResponseStatus {
    RESPONSE_STATUS_OK = 0;
    RESPONSE_STATUS_ERROR = 1;
}

message CreateUserGroupRequest {
    UserGroupTarget target = 1;
    string sam_group_name = 2;
    google.protobuf.StringValue description = 3;
}

message GroupRequest {
    UserGroupTarget target = 1;
    string sam_group_name = 2;
}

message UserGroupRequest {
    UserGroupTarget target = 1;
    string sam_group_name = 2;
    string sam_account_name = 3;
}

message UserGroupTarget {
    oneof target {
        laborato.mesh.operator.v1.GlobalTarget global = 1;
        laborato.mesh.operator.v1.AgentTarget agent = 2;
        laborato.mesh.operator.v1.UserTarget user = 3;
        laborato.mesh.operator.v1.TacticalClientTarget client = 4;
        laborato.mesh.operator.v1.TacticalClientsTarget clients = 5;
        laborato.mesh.operator.v1.TacticalSiteTarget site = 6;
        laborato.mesh.operator.v1.TacticalSitesTarget sites = 7;
        laborato.mesh.operator.v1.AggentsTarget agents = 8;
        laborato.mesh.operator.v1.CombinedTarget combined = 9;
  }
}
