name: Deploy to Server (Develop)
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_STAGE }}
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER_STAGE }}@${{ secrets.SSH_HOST_STAGE }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm use 20
          
          node -v
          npm -v
          
          cd ~/mdmlabsrmm/web-tactical/

          echo "🌐 Pulling latest changes..."
          git pull

          echo "♻️ Restoring local package.json..."
          mv package.json.local package.json || true

          echo "📦 Installing dependencies..."
          npm install --legacy-peer-deps

          echo "🔧 Generating proto files..."
          npm run proto:generate

          echo "🏗️ Building project..."
          npm run build
          
          cd ~/mdmlabsrmm/
          echo "🐳 Building Docker image..."
          docker build --pull --no-cache -t "mdmlabs-frontend" -f "docker/containers/mdmlabs-frontend/dockerfile" .
          echo "🛑 Stopping frontend container..."
          docker stop mdmlabs-frontend || true
          echo "🗑️ Removing frontend container..."
          docker rm mdmlabs-frontend || true
          echo "🚀 Starting new frontend container..."
          cd ~/mdmlabsrmm/docker/
          docker compose up -d mdmlabs-frontend
          
          EOF
